openedx/repo-tools

- people.yaml
wrong name. Cut and paste error. 
@singingwolfboy
> Fix Aamir's info

- people.yaml
@nedbat or @singingwolfboy, @ahsan-ul-haq will be helping out with escalation and accessibility issues.
> adds ahsan ul haq from arbisoft

- people.yaml
@aleffert do you know the names of the Clarice contributors & can you help me out w/ them here?
> Add names for clarice users

- people.yaml
> Add swapnali-clarice to people list

- people.yaml
See https://openedx.atlassian.net/browse/DEVOPS-1162 and https://openedx.atlassian.net/browse/CRI-3. @nedbat, is this the correct syntax?
> Remove Alex Kryklia (no longer an edx employee)

- people.yaml
> Add Hanning Ni and Divakar Patil

- people.yaml
> Expire the clarice iOS team

- people.yaml
> Add Ehmad Zubair, Ibraheem Zaman, expire rest of Clarice

- jiraspider.py
@nedbat this is the bug you ran into when first running the script.
> Fix bug related to newly-opened issues with no transitions yet

- jiraspider.py
- longest_tickets.py
see https://openedx.atlassian.net/browse/OPEN-649
TODO
> Script to get longest tickets and tix sorted by length per state OPEN-649

- people.yaml
> add adam's gmail to people.yaml

- people.yaml
Adding myself to people.yaml, per @sarina
> Add Joel Barciauskas to people.yaml

- people.yaml
@nedbat, can you confirm that I'm doing the right thing here?
> Disable auraz

- tag_release.py
- tests/test_tag_release.py
@nedbat can you take a look at this?
> tag overrides

- tag_release.py
- tests/conftest.py
- tests/test_tag_release.py
We should probably rename this script...
@nedbat
> Allow branches

- edx_repo_tools/oep2/explode_repos_yaml.py
> Make openedx.yaml process idempotent, so that it can be resumable

- dev-requirements.in
- dev-requirements.txt
- requirements.in
**Depends on PR #61*
/cc @cpennington
> [DEPS #61] Be more explicit about why we include pytest in our base requirements

- requirements.in
- requirements.txt
- webhookdb.py
> Add webhooks.py back into the repo

- edx_repo_tools/release/tag_release.py
> Remove unneeded variable assignment

- edx_repo_tools/release/tag_release.py
- tests/test_tag_release.py
tag_releases no longer tags dependent repos.
> Remove dependent repo support

- edx_repo_tools/oep2/checks/check_oep2.py
Responding to changes in OEP-2.
Please review @cpennington
> Do not require an owner for archived repos.

- .gitignore
- edx_repo_tools/gitgraft/README.md
- edx_repo_tools/gitgraft/gitgraft.py
- edx_repo_tools/gitgraft/gitgraft_modulestore
- edx_repo_tools/gitgraft/gitgraft_platform_core
- edx_repo_tools/gitgraft/requirements.txt
Per advice over in the tubular repo I'm moving this tool over here.
> Adding gitgraft tool

- barcalendar.py
@feanil I don't know if you want to see these things before I merge them?
> Reimplement barcalendar

- barcalendar.py
Our forums service currently runs on ruby.
https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=417264012
> Add ruby to the support windows sheet.

- django2_codemods/README
- django2_codemods/foreignkey_on_delete_mod.py
Adding on_delete for models.OneToOneField.
> Adding on_delete for models.OneToOneField.

- edx_repo_tools/dev/clone_org.py
- edx_repo_tools/gitgraft/requirements.txt
- requirements/base.txt
- requirements/development.txt
- requirements/pip-tools.txt
Reverts edx/repo-tools#109
Jumped the gun on this a bit.
> Revert "Feanil/get clone org working"

- django2_codemods/widget_add_renderer_mod.py
BOM-1147 -- Createf a code mod for adding renderer argument in Widget.render method.
> BOM-1147 -- Create a code mod for Widget.render change

- django3_codemods/script_to_replace_static.sh
Relevant JIRA : [https://openedx.atlassian.net/browse/BOM-1512](https://openedx.atlassian.net/browse/BOM-1512)
> BOM-1512 : Replace deprecated loadstatic and admin_static syntax

- django3_codemods/config_tools/tox_modernizer.py
- tests/sample_tox_config.ini
- tests/sample_tox_config_2.ini
- tests/test_tox_modernizer.py
relevant JIAR issue [here](https://openedx.atlassian.net/browse/BOM-1508).
> Added tox modernizer to update tox configurations -- BOM-1508

- .travis.yml
**Issue:** [BOM-1507](https://openedx.atlassian.net/browse/BOM-1507)
- Ran `travis_modernizer` on the `.Travis.yml` file to update python versions.
> BOM-1507 Updated Travis python && django

- edx_repo_tools/dev/get_org_repo_urls.py
Should we write tests for these functions?
> Fix get-org-repo-status script.

- edx_repo_tools/auth.py
Adds ability to log into github with a token taken from file -- or from a process substitution pipe like `<(gpg --decrypt ...)`, which allows you to keep your secrets from actually hitting disk.
> Add `--token_file` option to Github auth

- django3_codemods/replace_unicode_with_str.py
https://openedx.atlassian.net/browse/BOM-1973
> Add codemod to replace __unicode__ with __str__ -- BOM-1973

- edx_repo_tools/gitgraft/requirements.txt
- edx_repo_tools/modernize_openedx_yaml.py
- requirements/base.in
- requirements/base.txt
- requirements/development.txt
- requirements/pip-tools.txt
- setup.py
- tests/sample_openedx.yaml
- tests/test_modernize_openedx_yaml.py
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1974).
> Added yaml modernizer to remove deprecated elements from openedx.yaml

- .travis.yml
- setup.py
https://openedx.atlassian.net/browse/BOM-1976
> Add deploy to pypi option in travis.yml

- django3_codemods/__init__.py
- django3_codemods/config_tools/github_actions_modernizer.py
- tests/sample_files/sample_ci_file.yml
- tests/sample_files/sample_ci_file_2.yml
- tests/test_actions_modernizer.py
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2163
> BOM-2163 : Add Github Actions Modernizer

- edx_repo_tools/gitgraft/requirements.txt
- requirements/base.in
- requirements/base.txt
- requirements/development.txt
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2346
> BOM-2346 : Remove Sqlalchemy

- edx_repo_tools/gitgraft/requirements.txt
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/development.in
- requirements/development.txt
- requirements/gitgraft.in
- requirements/pip-tools.in
- requirements/pip-tools.txt
- requirements/pip.in
**Issue:** [BOM-2551](https://openedx.atlassian.net/browse/BOM-2551)
- `code-annotations==1.1.1` && `edx-lint==5.0.0` both require `click<8.0.0` so pinned the `click` package version.
> BOM-2251: Add constraints.txt to pin packages

- edx_repo_tools/conventional_commits/commitstats.py
- edx_repo_tools/utils.py
Though there's no built-in reporting yet, you have to do manual queries against the SQLite database.
> feat: add squad data to conventional_commits

- edx_repo_tools/codemods/django3/__init__.py
- edx_repo_tools/codemods/django3/github_actions_modernizer_django.py
- setup.py
- tests/sample_files/sample_ci_file.yml
- tests/sample_files/sample_ci_file_2.yml
- tests/sample_files/sample_ci_file_3.yml
- tests/sample_files/sample_ci_file_4.yml
- tests/sample_files/sample_ci_file_multiple_jobs.yml
- tests/test_actions_modernizer_django.py
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2610
> BOM-2610: Django modernizer for GH actions

- edx_repo_tools/codemods/django3/replace_render_to_response.py
- setup.py
- tests/sample_files/sample_render_to_response.py
- tests/sample_files/sample_render_to_response_2.py
- tests/test_replace_render_to_response.py
Add Django 3 codemod to rename render_to_response to render and add request parameter
JIRA: [BOM-2666](https://openedx.atlassian.net/browse/BOM-2666)
> feat: add django 3 codemod to rename render_to_response to render

- edx_repo_tools/codemods/django3/add_new_django32_settings.py
- setup.py
- tests/sample_files/sample_django_settings.py
- tests/sample_files/sample_django_settings_2.py
- tests/test_add_new_django32_settings.py
**Issue:** [BOM-2716](https://openedx.atlassian.net/browse/BOM-2716)
- Add new settings for `Django32` upgrade.
> BOM-2716: Codemod for adding new django32 settings

- README.rst
> doc: update broken link

- .github/workflows/pypi-publish.yml
- setup.py
JIRA: https://openedx.atlassian.net/browse/BOM-2815
> build: Updated the workflow to trigger release on tags

- edx_repo_tools/codemods/django3/github_actions_modernizer.py
- edx_repo_tools/codemods/django3/github_actions_modernizer_django.py
Updated indentation settings in YamlLoader class in this [PR](https://github.com/openedx/repo-tools/pull/255) so removing indentation settings from inherited classes.
> refactor: Removed redundant indentation settings

- edx_repo_tools/dev/clone_org.py
@kdmccormick yet another flag.
> feat(clone_org): a --forks-only flag

- barcalendar.py
- Updated support windows data according to the steps mentioned in the respective `endoflife` docs.
- After the PR is merged, the data on the sheet will be updated manually according to the steps mentioned in the script.
> docs: update support windows data

- barcalendar.py
https://nodejs.org/en/blog/announcements/nodejs16-eol/
> fix(barcalendar): node 16 moved their end date

- barcalendar.py
Also adjust the extra rows and columns, and which years are displayed.
> fix: palm is the latest release

- barcalendar.py
The resulting sheet looks like this: https://docs.google.com/spreadsheets/d/1TEu4ZToH3cEZ_Hf_l-IH7VOSruNiru-YzvwVfTPlH_U/edit?usp=sharing
> feat(barcalendar): add footnotes to bars, and Ruby is 3.0

- edx_repo_tools/repo_checks/labels.yaml
Add some new process labels for managing Open edX contributions.
> feat: Update labels.yaml

- barcalendar.py
The results are in the Draft Update tab: https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=649002970
I'll add a README tab that explains things too.
> feat(barcalendar): add edx production details

- edx_repo_tools/repo_checks/labels.yaml
For https://github.com/openedx/axim-engineering/issues/957
> feat(labels.yaml): `jira:2u` label for auto-creating Jira issues

- edx_repo_tools/repo_checks/repo_checks.py
Details:
https://github.com/openedx/axim-engineering/issues/1096
> temp: disable auto-merge only for edx-platform

- barcalendar.py
Update the link to the sheet that contains the data to one under Axim control.
> docs: Update barcalendar.py

- edx_repo_tools/repo_checks/labels.yaml
Addresses https://github.com/openedx/axim-engineering/issues/1212
> build: Add FC label for Axim project management
