openedx/repo-tools

- .gitignore
- helpers.py
- monthly_pr_stats.py
- pull_quarters.py
New script to calculate pull requests opened and their current status by month.
Returns the raw # of PRs opened, and their resultant state in a table:
Month | #merged | #rejected | #unresolved | #opened |
Note that this means the stats will change over time until all PRs are resolved. The sum of the first three data columns (#merged, #rejected, #unresolved) must equal the final column (#opened).
This data can be used to make cool graphs:
> Bucketed per-month PRs

- .gitignore
- jiraspider.py
- requirements.txt
- transitions_kpi.py
We'll measure the time pull requests spend waiting for edX to do their work on them.  We'll track this to understand how responsive we are being to contributors' needs. Initial measurements will be across all of engineering, without individual team statistics.
https://openedx.atlassian.net/wiki/display/OPEN/Tracking+edX+Commitment+To+OSPRs
> Transition KPI: Scraping and parsing scripts

- transitions_kpi.py
Refactor Transitions KPI script to make it easy to add new statistical analysis.
Script reports average by default. Other statistics that can now be reported: percentile, median, max, min, and standard deviation.
```
$ python transitions_kpi.py -h
usage: transitions_kpi.py [-h] [--no-scrape] [--since DAYS] [--debug]
[--pretty] [--average] [--median]
[--percentile PERCENTILE] [--std-dev] [--max]
[--min]
Summarize JIRA info.
optional arguments:
-h, --help            show this help message and exit
--no-scrape           Don't re-run the scraper, just read the current
states.json file
--since DAYS          Only consider unresolved PRs & PRs closed in the past
DAYS days
--debug               Show debugging messages
--pretty              Pretty print output
--average             Print out the …
```
> Transitions kpi refactoring

- dev-requirements.txt
- requirements.txt
- tag_release.py
- tests/conftest.py
- tests/test_tag_release.py
This `tag_release.py` script will tag repositories for Open edX releases. It accepts one argument, the name of the tag to create. It determines which commits need to be tagged in which repos, and asks for confirmation. Then it uses the GitHub API to create tags on all the repos. There are also automated tests to cover the most important functionality of the script.
Relies on https://github.com/edx/repo-tools-data/pull/5
> Add script to tag repos for Open edX releases

- edx_repo_tools/release/tag_release.py
- edx_repo_tools/utils.py
The --dry/--yes flag conflicted with tag_release's --yes flag, which btw
was broken. Now it's --dry/--doit, and --yes is back to its original
meaning.
> Fix --dry and --yes

- edx_repo_tools/release/tag_release.py
A recent change changed the repo info dict keys from strings to Repo objects.  This broke `--override`, which is fixed here.  I also wanted to sort the output by repo name, which touched on the same string->Repo change.
> Sort the output, and fix overrides

- .travis.yml
- Jenkinsfiles/openedx-release-ci
- edx_repo_tools/release/tag_release.py
Get the ball rolling on an openedx-release-ci job to test/automate creating releases. So far this will just use the tag_release script to create branches in the necessary branches with a bot I created @openedx-release-bot , and delete them if the DSL parameter tells it to. I also changed one line in the tag_release script to raise an exception rather than just printing to the console, so that the build will fail if that condition is hit.
> Add jenkinsfile for openedx-release-ci job

- django2_codemods/widget_add_renderer_mod.py
I inverted the condition because function imports was causing problems alongside function call, so instead of adding a new condition, I inverted condition that it should only work on function definitions.
> Inverted condition of render function filteration

- django3_codemods/config_tools/travis_modernizer.py
- tests/test_travis.yml
- tests/test_travis_2.yml
- tests/test_travis_modernizer.py
**Relevant Issue:** [BOM-1507](https://openedx.atlassian.net/browse/BOM-1507)
Travis Modernizer script performs the following operations on a given `Travis` file:
- Remove Django versions `1.11`, `2.0` && `2.1`
- Remove Python `3.6` from test envs.
- Add Python `3.8` to test envs.
> Added travis modernizer to update travis configurations

- barcalendar.py
We're now targeting an upgrade to Elasticsearch 7.8, not 7.3.  Update the relevant support window bar accordingly.
> Update Elasticsearch 7 info for the 7.8 release being targeted

- django3_codemods/config_tools/github_actions_modernizer.py
- setup.py
- tests/sample_files/sample_ci_file_3.yml
- tests/test_actions_modernizer.py
The cleanup job was failing on multiple repos when ran with this modernizer because we are using inconsistent test sections name in Github ci.yml files, so handled those edge cases.
> Fix Github Actions modernizer

- edx_repo_tools/dev/get_org_repo_urls.py
- setup.py
We want to ignore a repo which was created as part of a test of GitHub's security advisory process, during repo-health-dashboard checks run
Issue: [BOM-2472](https://openedx.atlassian.net/browse/BOM-2472)
> feat: added --ignore-repo flag in get_org_repo_urls command

- barcalendar.py
@jmbowman what is the right way to choose elasticsearch versions to show?
> fix: update barcalendar.py for elasticsearch and node versions

- edx_repo_tools/dev/clone_org.py
When repos are removed from GitHub, now "clone_org --prune" will remove
those directories.
> feat: clone_org can remove obsolete directories

- edx_repo_tools/dev/get_org_repo_urls.py
Now that we are collecting repos for multiple organizations we need to append the output to the file instead of overwriting it on existing content.
See https://github.com/edx/jenkins-job-dsl-internal/pull/591
> fix: append instead of overwrite for repos file

- edx_repo_tools/codemods/node16/gha_ci_modernizer.py
We're going to deploy things on Node 16 now so updating the modernizer to drop support for older versions of Node
> build: Dropped older node versions

- edx_repo_tools/oep2/explode_repos_yaml.py
- edx_repo_tools/release/tag_release.py
The edx-solutions organization no longer exists, and it causes a 404 error in
the tag_release script:
tag_release --branch --dry open-release/nutmeg.master
...
Traceback (most recent call last):
File ".../repo-tools/.venv/bin/tag_release", line 33, in <module>
sys.exit(load_entry_point('edx-repo-tools', 'console_scripts', 'tag_release')())
File ".../repo-tools/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File ".../repo-tools/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File ".../repo-tools/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File ".../repo-tools/.venv/lib/python3.9/site-packages/click/core.py", line 610, …
> fix: github 404 in tag_release script

- edx_repo_tools/release/tag_release.py
Every time I run tag_release, I need to remember what some of the
options do. This time I've decided that I should finally add some words
to explain the general usage of the script. The extra information is
printed when we run `tag_release --help`. For information, the "\b"
lines in the docstring prevent Click from automatically re-wrapping the
following line:
https://click.palletsprojects.com/en/8.1.x/documentation/#preventing-rewrapping
> docs: improve `tag_release` CLI help

- Makefile
I thought all repos had one of these.  It's better with it.
> build: add a help target to the Makefile

- edx_repo_tools/auth.py
I've been moving to having credentials in the environment rather than in
files on disk.  After deleting .netrc, repo-tools `clone_org` prompts
for a username and password.  This change lets it read a token from the
environment instead.
> feat: read GITHUB_TOKEN env var for authentication

- .github/workflows/support-window-issue-creator.yml
- Added workflow to create recurring issues each quarter to update Support Windows Sheet.
- Closes https://github.com/edx/edx-arch-experiments/issues/85
- Tested the workflow to be working by adding `pull_request` flag in the workflow execution
- https://github.com/openedx/repo-tools/issues/345 was created as a result.
> Add recurring support windows workflow

- edx_repo_tools/conventional_commits/commitstats.py
I use this line in a Makefile:
```
conventional_commits collect --ignore='*-private' edx/* openedx/*
```
Usually the openedx directory only has directories in it (cloned repos).  But I had a file in there at one point which stopped my command from working.  This fix will simply skip arguments that aren't directories.
> fix(conventional_commits): skip non-dir arguments

- edx_repo_tools/dev/clone_org.py
When I clone the openedx org, I don't want to clone "edx-platform-ghsa-wxyz-0123-abcd".  This option lets me ignore those temporary security-patch repos.
> feat(clone_org): add --ignore for globbed repos to ignore

- Makefile
- edx_repo_tools/conventional_commits/extra.txt
- edx_repo_tools/find_dependencies/extra.txt
- requirements/base.txt
- requirements/development.txt
- requirements/pip.txt
- `pip.txt` wasn't being updated in the `make upgrade` job because the `--upgrade` flag was missing in the `pip-compile` command
- It was causing the scheduled `Python Requirements Upgrade` [build](https://github.com/openedx/edx-django-utils/actions/runs/4847705622/jobs/8666288926#step:5:28) to fail due to `pip & pip-tools` conflict.
> fix: enable updating pip.txt in make upgrade

- edx_repo_tools/repo_checks/repo_checks.py
Formerly, the universal triage team was named `community-pr-triage`.
Axim decided that we'd like to grant triage access to everyone in the org, not just PR triagers.
So, we choose the name `openedx-triage`, per https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Team+Naming+Conventions
Other small changes:
* docs: link to original terraform-github source in docstring
* fix: generated PRs should link here, not terraform-github
* Rename the team in the GitHub UI
* Run `repo_checks -c RequireTriageTeamAccess` to ensure it's a no-op.
* Either:
* Open an issue for adding a new type of check (a `TeamCheck`??) which would ensure that every org member is on the team, automatically.
* Go the manual route:
* add everyone to openedx-triage by hand
* update our process docs to …
> feat: rename universal triage team to openedx-triage

- edx_repo_tools/conventional_commits/extra.txt
- requirements/constraints.txt
The bug report: https://github.com/pudo/dataset/issues/419
Without the pin, this error happens when running this command:
```
$ conventional_commits collect --ignore='*-private' edx/* openedx/*
Traceback (most recent call last):
File "/usr/local/virtualenvs/repo-tools/bin/conventional_commits", line 33, in <module>
sys.exit(load_entry_point('edx-repo-tools', 'console_scripts', 'conventional_commits')())
File "/usr/local/virtualenvs/repo-tools/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/virtualenvs/repo-tools/lib/python3.8/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/virtualenvs/repo-tools/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
return …
```
> build: pin alembic to avoid a dataset bug

- edx_repo_tools/conventional_commits/extra.txt
- edx_repo_tools/repo_access_scraper/extra.txt
- edx_repo_tools/repo_checks/extra.txt
- requirements/base.txt
- requirements/constraints.txt
- requirements/development.txt
- requirements/pip-tools.txt
- requirements/pip.txt
This bug: https://github.com/pudo/dataset/issues/419 has been fixed in
https://github.com/pudo/dataset/pull/423, so we don't need to pin
alembic anymore.
> Un-pin alembic, the incompatibility is solved.

- Makefile
- barcalendar.py
- edx_repo_tools/conventional_commits/commitstats.py
- edx_repo_tools/find_dependencies/README.rst
- edx_repo_tools/find_dependencies/find_dependencies.py
- edx_repo_tools/repo_access_scraper/repo_access_scraper.py
- edx_repo_tools/repo_checks/repo_checks.py
- requirements/development.in
- requirements/development.txt
- setup.py
I think pylint hasn't been run here in a very long time.  This removes pep8 which isn't called correctly, and fixes a few actual issues in modules I've touched recently.
> style: fix a few pylint alerts

- gittools.sh
`gittree` used to be `gittreeif @` on the theory that every git repo had @ (alias for HEAD).  But a git repo with no branches at all, not even main, has no HEAD.  Now that we have repos used exclusively for issues, we have to deal with zero commits, zero branches.
> fix(gittools): gittree wouldn't run in branchless repos

- barcalendar.py
edx.org has now also upgraded to Ruby 3.0.
> fix(barcalendar): remove obsolete Ruby note

- edx_repo_tools/find_dependencies/find_dependencies.py
When looking for the repos, we weren't following redirects from http to https, and so missed a number of repos.
See updated results in https://github.com/openedx/wg-build-test-release/issues/238
> fix(find-dependencies): http->https redirections weren't followed

- edx_repo_tools/find_dependencies/find_dependencies.py
When looking for the GitHub home of a PyPI package, if nothing is explicitly marked as Source or Home, use any Project-URL that is a GitHub repo.
This doesn't find us any more repos, but removes this noise line from the output:
```
No repo URL in files/shapely-2.0.1-cp38-cp38-macosx_10_9_x86_64.whl
```
> fix(find_dependencies): use any github repo project-url if need be

- edx_repo_tools/find_dependencies/find_dependencies.py
This lets us find where `wheel` is hosted on GitHub.
> fix(find_dependencies): a GitHub issues URL can point us to the repo.

- edx_repo_tools/repo_checks/labels.yaml
I'll apply this by running `repo_checks -c EnsureLabels --no-dry-run`.
> feat: add `backport` label to all repos

- barcalendar.py
- PR created under the issue https://github.com/openedx/repo-tools/issues/445 to update the Support Windows Sheet on quarterly basis.
- The generated JS code has successfully been updated on the Support Windows Sheet linked to the issue.
> fix: update barcalendar script with latest changes

- barcalendar.py
- Updated the `barcalendar` script instructions to avoid confusion when updating the Support Windows sheet. 
- Fixed year value for Ubuntu data in the checks. 
- Updated the support window sheet (https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=195838733) with updated data.
> fix: update barcalendar script usage instructions

- edx_repo_tools/repo_checks/repo_checks.py
"When using a paged API endpoint, I want an iterable of pages" -- No one ever.
This helper lets us focus on the things we care about: the items we are asking for.
> refactor: a helper for paged results

- barcalendar.py
I already ran it on the chart: https://docs.google.com/spreadsheets/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=195838733
> feat(barcalendar): Sumac and Teak

- barcalendar.py
- added Quince to the openen release `names`
- removed Quince from `future` releases
- changed Django version to 4.2 for `EDX` and `CURRENT` (I'm not sure about this step cause in edx-platform/master we still have 3.2 and Ecommerce still on 3.2 too)
> chore: barcalendar Quince updates

- edx_repo_tools/repo_checks/repo_checks.py
For each repo, the check will find any teams that have admin or maintain
access to that repo and downgrade the access of the team to write.
> feat: Add a new check to ensure no teams have admin or maintain access.

- edx_repo_tools/repo_checks/repo_checks.py
This check looks at the settings on all repos and ensures that they are
set the same.  To begin with the following settings are ensured:
- Issues should be enabled.
- Wikis should be disabled.  The confluence wiki should be used.
- Allow auto-merge to be used. (Does not enable auto-merge, just allows committers to enable it on a per PR basis.)
- Branches should be deleted on merge.
> feat: Add a check to ensure certain settings are standardized.

- edx_repo_tools/release/tag_release.py
Repositories that contain only the catalog-info.yaml file are missing from the result list.
Result with this fix:
```
Find commits  45/45
```
Result w/o the fix:
```
Find commits 37/37
```
> fix: catalog only repos are missing in a release list

- edx_repo_tools/repo_checks/repo_checks.py
Ticket: https://github.com/openedx/repo-tools/issues/407
Adds check 'Users should not have direct repo access'
Run the following `repo_checks` command to test the checks.
```shell
repo_checks \
--org ORGANIZATION \
--repo REPO 
```
> Adds check 'Users should not have direct repo access'

- edx_repo_tools/repo_checks/labels.yaml
also: this chills out the shade of the
"release testing" label a bit so that the
"release blocker" label can really pop
* https://github.com/openedx/axim-engineering/issues/1129
* https://github.com/openedx/axim-engineering/issues/1130
> feat: add labels: release blocker, needs reviewer assigned

- tests/fake_repos/repo_with_nvmrc/.github/workflows/release.yml
- tests/fake_repos/repo_without_nvmrc/.github/workflows/release.yml
- tests/sample_files/sample_ci_file_2.yml
- tests/sample_files/sample_node_ci.yml
- tests/sample_files/sample_node_ci2.yml
Update codecov to the latest version and start using the org-wide token for uploads.
See https://github.com/openedx/wg-frontend/issues/179
> build: Update codecov and use token

- barcalendar.py
Changes:
- removed Redwood from future releases
- changed CURRENT and EDX version of everything
@feanil I didn't change Mongo, MySQL, Elasticsearch, Redis, Ruby for EDX. I need an info about the current software versions for edx.org.
> chore: barcalendar Redwood updates

- edx_repo_tools/repo_checks/README.rst
- edx_repo_tools/repo_checks/repo_checks.py
This check will make new PRs but there are times when we want to have certain repo/workflow exceptions where we don't want to mess with them from here and create extra churn.  So add a way to track that info in the check so we can encode that info up front as we learn it.
Sample output:
```
docs.openedx.org: 
Branch Protection with CLA Check is in Place. 'cla-checker' team has 'push' access.
'openedx-triage' team has 'triage' access.
All desired labels exist with the right name, color, description.
All desired workflows are in sync with what's in the .github repo.
Ignoring repo specific exceptions: ['commitlint.yml']
No teams with `admin` or `maintain` permissions.
All expected settings are set correctly.
Steps:
No changes needed.
No user has direct repo access.
```
> Add exceptions to the EnsureWorkflows check + Docs Update

- edx_repo_tools/repo_checks/repo_checks.py
Reverts openedx/repo-tools#505
This can be merged once https://github.com/openedx/edx-platform/issues/34789 is resolved.
> revert: temp: disable auto-merge only for edx-platform

- edx_repo_tools/pull_request_creator/__init__.py
- tests/test_pull_request_creator.py
- `set-output` has been deprecated by GitHub and it is suggested to be replaced by GitHub.
> fix: replace deprecated github actions

- edx_repo_tools/repo_checks/labels.yaml
As we focus more on performance issues like latency and memory usage across our various services, it's going to be useful to have a consistent, project-wide label to track these.
> feat: add 'performance' label to all repos

- edx_repo_tools/repo_checks/repo_checks.py
- tests/test_repo_checks.py
Rename teams to be a bit more consistent and brief.
Also, get rid of the hardcoded `CHECKS` list in exchange for a `@Check.register` decorator.
Before:
```
(venv) ~/openedx/repo-tools 🍀 repo_checks --help
Usage: repo_checks [OPTIONS]
Entry point for command-line invocation.
Options:
--github-token TEXT             A github personal access token.  [required]
--org TEXT                      The github org that you wish check.
-n, --dry-run / --no-dry-run    Show what changes would be made without
making them.
-c, --check [RequiredCLACheck|RequireTriageTeamAccess|EnsureLabels|EnsureWorkflowTemplates|EnsureNoAdminOrMaintainTeams|EnsureRepoSettings|EnsureNoDirectRepoAccessToUsers]
Limit to specific check(s), case-
insensitive.
-r, --repo TEXT                 Limit to specific repo(s).
-s, …
```
> Rename and decorate repo checks

- edx_repo_tools/repo_checks/repo_checks.py
Adds check to ensure org doesn't have any outside collaborator
**Ticket:** https://github.com/openedx/public-engineering/issues/169
**Git api used to add check:**
https://docs.github.com/en/rest/orgs/outside-collaborators?apiVersion=2022-11-28
**Use following command to test:**
```shell
repo_checks \
--org $ORGANIZATION \
--repo $REPO
```
> feat: Adds check to ensure org doesn't have any outside collaborator

- edx_repo_tools/pull_request_creator/__init__.py
As the PR title changed in this PR https://github.com/openedx/.github/commit/e2fbf6ddcba92cac7d879d2ef3eb6ce7de778d64, so updating the check accordingly.
> fix: Update PR title check during upgrade PR creation

- barcalendar.py
And update the version of Ruby we're on since that was out of date.
> feat: Add more dates to the bar calendar.

- edx_repo_tools/oep2/report/cli.py
This PR:
- replaces `pkg_resources` api from `importlib_resources` api
---
Ticket: [Move on from deprecated pkg_resources api](https://github.com/openedx/repo-tools/issues/555)
> repo-tools | Replace pkg_resources to importlib_resources

- edx_repo_tools/repo_checks/labels.yaml
Add a flaky-test label to be used as part of an updated flaky test process. See:
https://openedx.atlassian.net/wiki/spaces/AC/pages/4306337795/Flaky+Test+Process
The original process used the old edX Jira project, and this update is a part of moving this process to github.
> feat: add flaky-test label

- edx_repo_tools/repo_checks/labels.yaml
chore: Adds hactoberfest-accepted label
This PR is adding `hactoberfest-accepted` label because Hacktober participant's PR/MRs must be in a repo tagged with the “hacktoberfest” topic, or have the “hacktoberfest-accepted” label.
For further information: https://hacktoberfest.com/participation/
> chore: Adds hactoberfest-accepted label

- edx_repo_tools/repo_checks/repo_checks.py
This tema should have write access to all public repos.  They can do any
maintenance work in any public repo that is a part of the Open edX
platform.
> feat: Add a check to ensure the committers-at-large team has access.

- barcalendar.py
We are DEPR'ing the old ReadTheDocs site, so update links to edx.rtd.io to docs.openedx.org
Also updated the release calendar information with Sumac's release date and the names of upcoming releases
> docs: Update release notes link to docs.openedx.org

- edx_repo_tools/find_dependencies/find_python_dependencies.py
Using symmetric difference caused entries from the ignore list to be reported as 2nd party orgs in some cases. This appears to happen when the lookup fails for a package that matches something in the ignore list, and so its URL doesn't end up in `packages_urls`.
It's not clear what the nature of the failure is exactly (since we're not getting log messages about non-200 status codes) but we were seeing sporadic claims that `https://github.com/edx/codejail-includes` was found in the dependencies. The package on PyPI now actually is under the openedx org, so I believe this URL must have been coming from the ignore list.
We could add logging to discover what the failure mode is, but a lot of packages don't have a home URL, so it may not be simple to do this in a way that isn't noisy.
> fix: Compute diff properly in package home URL sets

- .github/workflows/support-window-issue-creator.yml
- `arbi-bom` team is soon going to be removed so removing the label from the issue.
- I would like to keep the ownership of these issues to continue working as open source contributor in the community.
> build: remove arbi-bom label from support window issues

- .github/workflows/support-window-issue-creator.yml
arbi-bom team project is not active anymore so the instruction to add this in a project for tracking should be removed now.
> docs: remove arbi-bom reference from support window issue description
